# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-01 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20170101_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='intro',
            field=models.CharField(blank=True, max_length=120, verbose_name='Book Introductory Highlight'),
        ),
    ]
